### ISSUE TITLE
Create a gh-pages branch and use to serve the HTML and IDL files.

### ISSUE THREAD

**Issue by dj2** [WICG/FedCM#105]
As a step towards not storing the rendered `html` and `idl` files in the repo (which cause a lot of noise during code review) can we create a `gh-pages` branch which can then be used by a GitHub action to render the files into and serve from GitHub pages?

**Comment by samuelgoto** [comment]
I have mixed feelings about this, but am happy to give this a try. As long as you are willing to educate me on the branches/generation of the bikeshed specs, I'm happy to learn new tricks! Approving now, merging, but heads up that I think this will make the workflow harder than it needs to be.

**Comment by dj2** [comment]
I flipped the configuration over to use the gh-pages branch now that the auto-gen workflow has landed. Closing this as complete. I'll file a followup to remove the files in the `docs` folder.
