### ISSUE TITLE
Determine how an IDP can do IDP frontchannel logout if the sign in occurred via a popup

### ISSUE THREAD

**Issue by pkotwicz** [WICG/FedCM#147]
Signing in to an RP via a popup is very common.

## Sample consumer cases:
- twitter.com "Sign Up with Google" button. (desktop site)
- twitter.com "Sign Up with Apple" button. (desktop site)
- boardgamearena.com "Create an account with Google" button (desktop site)
- boardgamearena.com "Create an account with Facebook" button (desktop site)

## Typical code flow:
1) RP calls [`UserAgentApplication#loginPopup()`](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal.useragentapplication.html#loginpopup) (Microsoft IDP) 
2) JavaScript API opens a popup in the IDP origin
3) IDP origin vends web page with username & password field
4) User enters username & password
5) IDP authenticates user
6) IDP popup calls back into RP (via `window.opener.postMessage()` I think) and notifies RP that sign in succeeded/failed. Notice the `AuthResponse` parameter of the Promise returned by `UserAgentApplication#loginPopup()`
  
```
      AuthResponse {  
          accessToken: string
          account: Account
          accountState: string
          expiresOn: Date
          fromCache: boolean
          idToken: IdToken
          idTokenClaims: StringDict
          scopes: string[]
          tenantId: string
          tokenType: string
          uniqueId: string
      }
```

7) IDP popup closes itself

## When third-party cookies are blocked:
- The RP will still be able to sign the user in thanks to the `AuthResponse` parameter in the promise returned by `UserAgentApplication#loginPopup()`
- The IDP will no longer be able to use "IDP Frontchannel Logout" for that specific RP
    - During IDP frontchannel logout, the IDP could open a popup for each RP URL that the IDP wants to logout but the RP would need to modify its "front channel logout URL" to call `window.close()`

#### Solution with IDP code changes & FedCM API changes:
1) In the signin popup, IDP calls navigator.credentials.store()
2) IDP will pass in RP origin for which it wants "logout permission".
3) If the IDP does not already have "logout permission" for the RP origin, the browser will display a browser UI prompt asking the user for permission (mediation)

**IDP change**
Call navigator.credentials.store() from the IDP popup.

**FedCM API change**
- Delete from the store algorithm outlined in 4.2.3:
  `Return a "NotAllowedError" DOMException without altering the user agent’s credential store if sameOriginWithAncestors is false.`
- Adding an explicit "origin" parameter to navigator.credentials.store() API enabling IDP to request logout permission for arbitrary RP origin.

Pros:
- No RP code changes

Cons:
- Need to relax navigator.credentials.store() API

### Solution with RP code changes:
RP would call navigator.id.store() in the loginPopup() callback.

Pros:
navigator.credentials.store() API does not need to change

Cons:
- IDP can no longer distribute their identity library over github (Ex: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core)
- IDP needs to contact all of the enterprise RPs that integrate with them and tell them to switch to an updated version of their identity library.
  - Migration seems difficult:
      - Note the number of Microsoft identity libraries (and maintenance mode libraries) [here](https://github.com/AzureAD/microsoft-authentication-library-for-js):
      - Google is in the process of moving [Google API Client Library for JavaScript](https://github.com/google/google-api-javascript-client/)  to maintenance mode - [news release](https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html)
- Any RPs who chose to use the auth code grant flow directly instead of using the RP's JavaScript library need to update their code

**Comment by dj2** [comment]
I'm confused, do those cases provided have a front channel logout capability? How do you trigger it, the use case seems to be login exclusively?

The current spec lists the `navigator.credentials.store()` call from the IDP under the IDP sign in section. This approach has other concerns around setting context for a different origin. We've started writing some of that down in #146. I'm of the mind that we should remove the current IDP sign-out section as written and determine if there is another approach.

For the second case, why can't the JS library be distributed over github anymore? The RP is changing the callback that is executed when the login is complete, is that not code controlled by the RP, but by the IDP? If it's controlled by the RP then it's outside the library and unaffected by it. If it's part of the library, the IDP can just change it.

**Comment by pkotwicz** [comment]
> I'm confused, do those cases provided have a front channel logout capability? How do you trigger it, the use case seems to 
> be login exclusively?
No, the cases I listed do not provide "front channel logout" ability because they are consumer websites. You are asking for an example of an enterprise website that
1) Has "front channel logout"
2) Uses a popup to get the user's credentials
I am unaware of any enterprise websites which support IDP front channel logout. If you want I can register for trial accounts for a bunch of enterprise apps and investigate.

> The current spec lists the navigator.credentials.store() call from the IDP under the IDP sign in section. This approach has 
> other concerns around setting context for a different origin. We've started writing some of that down in #146. I'm of the mind > that we should remove the current IDP sign-out section as written and determine if there is another approach.

I don't understand why setting context for a different origin is a concern.
In my opinion navigator.credentials.store() should work as long as either:
Option #1: FederatedCredential.provider is same-origin as the caller's environment settings object browsing context (and parent browsing contexts)
OR
Option #2: Caller’s environment settings object is same-origin with its ancestors

For the second case, why can't the JS library be distributed over github anymore? The RP is changing the callback that is executed when the login is complete, is that not code controlled by the RP, but by the IDP? If it's controlled by the RP then it's outside the library and unaffected by it. If it's part of the library, the IDP can just change it.

I should have been clearer. There are two subcases in the "RP code changes".
- Subcase #1: RP JavaScript is modified.
  RP calls navigator.id.store() in the loginPopup() callback. You are right that this is outside the IDP JavaScript library.
- Subcase #2: IDP JS library is changed to call navigator.id.store()
  The IDP needs to create a new version of the IDP JS library and tell all RPs which integrate with them to use the new version of the library.
  The IDP has three options:
   - Option A: Create a library with a new name (Ex: Microsoft Authentication Library for JavaScript v3.x)
   - Option B: Tell RPs to point to the IDP library on hosted on an IDP server (vs pointing to a copy hosted on the RP's server)
       The Google IDP has switched to telling RPs to include the IDP JS Library hosted on a Google server - https://apis.google.com/js/platform.js?onload=renderButton
   - Option C: Push a change to the repo containing the current IDP library. Tell RPs to check whether they have the latest version and if not re-clone the IDP library from github.

"why can't the JS library be distributed over github anymore" refers to "Option B"

**Comment by dj2** [comment]
We can leave the question open if front channel logout after a popup window signin happens in the wild to others who have enterprise accounts setup in this fashion. It doesn't seem like something that is easily testable.

One issue with setting the origin is allowing a third-party to set context for another party. There are potential security considerations in that case, and possibily privacy issues. Could that bit be used for tracking? Could the RP use it as a way to communicate with an external party? I think a lot more investigation would have to go into the security/privacy considerations of allowing one origin to set information for another origin would have to happen before we could consider allowing it. @kenrb may have more information.

I'm not sure I understand your option 2 in the case of setting origin. Are you saying when the popup is open, there is some form of context object in the browser which contains the RP as the originating origin? Is that in the spec, or something Chrome does?

For your subcase 2, that's software distribution. It's the same issue as if there was a critical security vulnerability or new software feature. I'm guessing a lot of this code is on CDNs and they'd push their change there after commiting to the repo. If the RP uses the CDN version they're fine, if they don't they'll need to upgrade. Same as with a security issue in the library.

**Comment by kenrb** [comment]
I believe we are talking about the identity provider using `navigator.credential.store` to store a credential that will go in the relying party's credential store, as in [section 7.2.2](https://wicg.github.io/FedCM/#browser-api-idp-sign-in)?

This is essentially using an API that is designed for site-specific storage as a cross-site communications channel, which sounds like a risky mismatch of expectations. For an RP, this could create a situation where they are pulling credentials out of your store with `get()`, and they don't necessarily know which ones were added by them or by someone else.

It is probably okay to have a Javascript method that the IdP can use to send a token to an RP (the explainer had suggested there could be a `provide()` method, though for a slightly different use case). However, that should be kept separate from credential storage.

**Comment by pkotwicz** [comment]
> I'm not sure I understand your option 2 in the case of setting origin. Are you saying when the popup is open, there is some
> form of context object in the browser which contains the RP as the originating origin? Is that in the spec, or something
> Chrome does?

In plain words, I think that we should allow navigator.credential.store() as long as either the IDP URL or the RP URL matches the URL of the containing browsing context.

In Option 2, I am referring to section 2.2.1.3 of the Credential Management Level 1 API
`[[Store]](credential, sameOriginWithAncestors) is called in parallel with a Credential, and a boolean which is true iff the caller’s environment settings object is same-origin with its ancestors.`

> I believe we are talking about the identity provider using navigator.credential.store to store a credential that will go in the 
> relying party's credential store, as in section 7.2.2?
I am referring to [section 4.2.3 in the Credential Management Level 1 API](https://www.w3.org/TR/credential-management-1/#store-federatedcredential), but I think that section 7.2.2 in the Federated Credential Management API is similar.

> This is essentially using an API that is designed for site-specific storage as a cross-site communications channel, which
> sounds like a risky mismatch of expectations. For an RP, this could create a situation where they are pulling credentials out of > your store with get(), and they don't necessarily know which ones were added by them or by someone else.

> It is probably okay to have a Javascript method that the IdP can use to send a token to an RP (the explainer had suggested 
> there could be a provide() method, though for a slightly different use case). However, that should be kept separate from
> credential storage.
- Can you point me to the provide() method in the explainer?

**Comment by dj2** [comment]
> In plain words, I think that we should allow navigator.credential.store() as long as either the IDP URL or the RP URL matches the URL of the containing browsing context.

Right, that's my question. When you create the popup window, do you know what the origin was that opened the popup?  Is that part of the spec? If the browser don't know the RP origin in the IDP popup, then you can't match the RP URL?

So, the part I don't understand is what "containing browser context" means. Is that part of the spec somewhere? What information provides it?

From a privacy standpoint, if 2 RPs decide to collude, then can they set tokens for each other by setting the credential into each others origins?

**Comment by pkotwicz** [comment]
>> In plain words, I think that we should allow navigator.credential.store() as long as either the IDP URL or the RP URL matches 
>> the URL of the containing browsing context.

> Right, that's my question. When you create the popup window, do you know what the origin was that opened the popup? Is
> that part of some spec? If the browser don't know the RP origin in the IDP popup, then you can't match the RP URL?

I am suggesting that we should allow navigator.credential.store() as long as EITHER
Option 1: the IDP URL matches the calling browsing context
Option 2: the RP URL matches the calling browsing context

In the case of an IDP popup, the IDP URL matches the containing browsing context.

It looks like the popup can access the URL of its opener via window.opener.location.href

> So, the part I don't understand is what "containing browser context" means. Is that part of the spec somewhere? What
> information provides it?

Sorry for the confusion. I mean "calling browsing context" as described in [section 4.2.1](https://www.w3.org/TR/credential-management-1/#collectfromcredentialstore-federatedcredential) of the "Credential Management Level 1" spec

> From a privacy standpoint, if 2 RPs decide to collude, then can they set tokens for each other by setting the credential into
> each others origins?
Yes and no.
My understanding is that the user will be prompted to accept credentials for each unique (RP, IDP) pair.
Once permission is granted by the user for a given RP to share information with a given IDP
- The IDP can set data on the RP's origin
- The RP can set data on its own origin
- The IDP cannot set data on its own origin
- The RP cannot set data on the IDP's origin

Yes, the FedCM API would enable the RP & IDP to talk to each other:
- This is the very thing that the user is granting consent for via a user agent prompt
- The IDP is sending to the RP a unique user identifier on sign in. Once the RP has received a token from the IDP the user agent cannot prevent the RP & IDP from colluding.

**Comment by dj2** [comment]
> In the case of an IDP popup, the IDP URL matches the containing browsing context.
> 
> It looks like the popup can access the URL of its opener via window.opener.location.href
> 

That was what I was looking for. We needed some way to get the RP URL that wasn't just the IDP telling it to us otherwise they could tell us anything. The question with `window.opener.location.href` is if it's reliable? If the IDP can overwrite it with something else, it maybe useless to us.


> > My understanding is that the user will be prompted to accept credentials for each unique (RP, IDP) pair.
> > Once permission is granted by the user for a given RP to share information with a given IDP
> 
> * The IDP can set data on the RP's origin
> * The RP can set data on its own origin
> * The IDP cannot set data on its own origin
> * The RP cannot set data on the IDP's origin

Yes, my question is how do you _know_ the RP URL on the IDP side? If the opener href gives it to us that works, but if the IDP change change that href, then we don't know the RP URL anymore.


> Yes, the FedCM API would enable the RP & IDP to talk to each other:
> 
> * This is the very thing that the user is granting consent for via a user agent prompt

Well we're granting permission for some data sharing, not unconditional sharing. We don't allow access to things like scopes at the moment, we do grant access to some bit of user PII.


> * The IDP is sending to the RP a unique user identifier on sign in. Once the RP has received a token from the IDP the user agent cannot prevent the RP & IDP from colluding.

We currently don't do anything about link decoration, but we may in the future. We will be preventing 3rd party cookies, so that info isn't sent anymore. So, yes, we aren't currently stopping all forms of collusion, but we'd like to have this API lock it down a bit more in how they can collude.

The other concern is if the ability to set the credential can be used as a way to fingerprint a user. Could this somehow be used to track users across sites by being able to set the credential for a differnet origin.

**Comment by dj2** [comment]
So, if I understand correctly, this is asking for what's currently in the spec in section 7.2.2. The main question coming out of this is how do we support the functionality which is tracked in #146 correct?

If so, can this be closed?

**Comment by pkotwicz** [comment]
Sure let's continue the conversation on #146
