### ISSUE TITLE
Diagram impossible to read in dark mode

### ISSUE THREAD

**Issue by yoavweiss** [WICG/FedCM#87]
https://github.com/WICG/WebID/blob/main/static/mock38.svg is dark text/lines over a transparent background, hence impossible to read in dark mode. A light background would probably be good enough.

**Comment by dj2** [comment]
I've updated the spec to put a white background behind the images. Is that sufficient or did you want the SVGs themselves updated?

**Comment by yoavweiss** [comment]
white background works great, thanks!
