### ISSUE TITLE
Abstract and Introduction in the Spec are unnecessarily broad

### ISSUE THREAD

**Issue by samuelgoto** [WICG/FedCM#90]
The current text in the abstract and introduction in the current spec that we are working on are unnecessarily broad:

https://wicg.github.io/FedCM/

> This specification defines a set of high-level APIs that enables users to continue to use Identity Providers to authenticate to Relying Partys without incurring into Unsanctioned Web Tracking. It accomplishes that by exposing the explicit user controls needed to manage the lifecycle of their federated accounts.

A few ways we can narrow this description down:

- to be precise about offering alternatives to federated sign in flows that break without third party cookies (i.e. that this spec is offered *in replacement of* third party cookies)
- to be precise about the non-mutually exclusive optionality of existing federated sign in flows with decorated links (i.e. that this spec is offered *in addition* to what currently works with decorated links -- whether/when/if it gets mitigated is left as a separate concern)
- to be precise about the narrow scope of account management (e.g. an account chooser) and session management (e.g. front channel logout)

**Comment by samuelgoto** [comment]
I like the text that @dj2 wrote in the README.md file and I think it matches a lot of the criteria here (and seems to be strictly better than what we currently have). I'm planning to use it in the spec as its abstract/introduction:

```
As the web has evolved there have been ongoing privacy-oriented changes (example) and underlying privacy principles. With those changes some underlying assumptions of the web are changing. One of those changes is the deprecation of third-party cookies. While overall good for the web, third-party cookie deprecation leaves holes in how some existing systems on the web were designed and deployed.

Federated Credentials Management API aims to fill the specific hole left by the removal of third-party cookies on federated login. Historically this has relied on third-party cookies or navigational redirects in order to function as they were the primitives provided by the web.

The explainer and spec provide a potential API and the rational behind how that API was designed.
```

**Comment by dj2** [comment]
I had a branch in progress where I was trying out some things in the abstract/intro. I've pushed it up as #141 to see if it's useful.
